name: Check code style with prettier

on: [pull_request, push]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install prettier
        run: yarn add --exact prettier

      - name: Check style
        run: yarn prettier -c .
