name: Deploy to GitHub Pages
on:
  push:
    tags:
      - "*"

jobs:
  build-deploy:
    runs-on: ubuntu-18,04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command

      - name: Build app
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn build` command

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
